# Generated by Django 5.2.5 on 2026-09-06 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOReplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('source_word', models.CharField(help_text='Слово или бренд, например айфон', max_length=100, unique=True)),
                ('replacement', models.CharField(help_text='SEO-замена, например iphone', max_length=100)),
            ],
            options={
                'verbose_name': 'SEO-замена',
                'verbose_name_plural': 'SEO-замены',
            },
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('lang', models.CharField(default='ru', help_text='Код языка, например ru или en', max_length=5)),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SEO-стоп-слово',
                'verbose_name_plural': 'SEO-стоп-слова',
                'constraints': [models.UniqueConstraint(fields=('lang', 'word'), name='unique_stopword_lang_word')],
            },
        ),
    ]
