# Generated by Django 5.2.5 on 2026-09-06 16:23

import apps.users.models.profile
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, help_text='Рекомендуется квадратное изображение', null=True, upload_to=apps.users.models.profile.avatar_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Аватар')),
                ('gender', models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской'), ('other', 'Другое'), ('not_set', 'Не указывать')], default='not_set', max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('voice_preference', models.CharField(choices=[('female', 'Женская озвучка'), ('male', 'Мужская озвучка'), ('neutral', 'Нейтральная озвучка'), ('auto', 'Подобрать автоматически')], default='auto', max_length=10, verbose_name='Предпочтение голоса')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('website', models.URLField(blank=True, default='', verbose_name='Сайт')),
                ('language', models.CharField(blank=True, default='ru', max_length=10, verbose_name='Язык интерфейса')),
                ('timezone', models.CharField(blank=True, default='Europe/Minsk', max_length=64, verbose_name='Часовой пояс')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('yandex', 'Yandex')], max_length=20, verbose_name='Провайдер')),
                ('provider_uid', models.CharField(max_length=255, verbose_name='UID провайдера')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Социальный аккаунт',
                'verbose_name_plural': 'Социальные аккаунты',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uniq_social_provider_uid')],
            },
        ),
    ]
